# Generated by Django 6.0.7 on 2026-08-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swiggy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
